sudo: required
dist: trusty
addons:
  apt:
    packages:
    - texlive-xetex
    - texlive-latex-extra
    - lmodern
    - texlive-latex-recommended
    - xzdec
    - texlive-fonts-recommended
script:
- tlmgr init-usertree
- tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
- tlmgr update --all
- tlmgr install etoolbox tcolorbox framed polyglossia hyperref pgf xcolor
- xelatex szofttech.tex
- xelatex szofttech.tex
deploy:
  provider: releases
  api_key:
    secure: aXobfMbQwseSys9RiP7fLgfT4tFKcPSiIUM7v2RrFaBbz4aX84sfrmK/aIPaSCZOvFdp+J+0hOMQuwuPXrKe++xuG7Fcjn8zQ8sX0pR7FSAVXzBNm4nhfXhNpmOY4jXuLv47N+y+Dkry4kaeZIkACm0ri/NeyAW2Rp5fuxSkG1ZL/bhiYk1EfmBVYs7xrTmIoSClP3nJ86TIWkaEjCd6gBfZEDlWzFDPnNKpLkSfNja3iOOGiUGwx2PFG9XcnoAK751wTye97147+XcLF/orgq+udXYcRWE2LMMFAzyUgmxPzYFfKqs5o36kLpwaRHeiInRyFdVgr9LbjPEntkAAlKY3leWlka9arPMXKlEuayOkYoMXtUIJ7I5XOxO+YiyUddac+pZiXx331FZBd9k4/sxu3umbuHpWWVoosK5jY5S8hQKfsCMz+wdgkAbm2jP1Fz0s1sBcHnaLwSFP8iMB1wb/RkUUhNgShPoXA8OI0rOoN0AngiZc3jDHS/uQjJydfTU3Z1PMM9HHKdwcbieO9zNUpQo8A5oQsp7P3+jaW8TxyRFvc78DkCLnRYoWler91TlmpekhcOpmbi+9hW8eDu1LTjZ7faMZ7VKZop6ohCYiiEUxRWq6T9bYBRw8yoTRykfJnauY39SjnXr6N/xtgNCFfslDpxkOa10IxbYD3d8=
  file: szofttech.pdf
  skip-cleanup: true
  overwrite: true
  on:
    repo: bme-notes/szofttech
