sudo: required
dist: trusty
addons:
  apt:
    packages:
    - texlive-xetex
    - texlive-latex-extra
    - lmodern
    - texlive-latex-recommended
    - xzdec
    - texlive-fonts-recommended
script:
- tlmgr init-usertree
- tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
- tlmgr update --all
- tlmgr install etoolbox tcolorbox framed polyglossia hyperref pgf xcolor
- xelatex szofttech.tex
- xelatex szofttech.tex
deploy:
  provider: releases
  api_key:
    secure: gFOjUsRnG1/Lfqyk4BSn4Nf2JtY9Au2ygLH7yWwdR2P8j6sG3B3/MeCFXpHJaCC4TeGMEXxlh8wzheynFN9cE8XWXW2M32IBJz/WxdjmKDpdrcQifq3ZmE/Rlv7k5BdwhEFaDusHvT6adpMQufOp4Xn4kwRPPWeRnZT1XO5+tPOqEJ1L3z+65jzWjbOA+WTRIEqJMU34OXOnCXJLTzqWA3RjIQlPcz6NeHV/iAh1D5dpBRnhLJyhInzUhg7ug7fmfdBwU7M6G8+up2PG4rURjOJy035pO5RnYDDxfDHnmDy7sUmGZK4ZNtZmINiMTqnHkE6k+T2TtRy5xk21FYUJxYnTxn5eL8Fj7MzQfeMkSvgh3OmEeP53zemcGXNR96CC1S/7IuzYrWFEgsEORD4ydlyYMHORzop4nSe3Ae6BfRw6yZXRe0iwoFih3Q8vVC4hSewCO9woF7K/cSGzaKfRwEA1nNZLxIp7u1I7LIa5djv2vCkQWX9DkicNaXhFBLMSBYTquSTaLSpI79BqP5r+LQqod+n78yl28Z9n6/h2jOwD1UTu4w3+55uiqAeGTjDITWik3F7C6t6Ynaz1paVW2zSlds0QoMNjloAkxt0iffcn3laYg6caVzHDMD3GWlbbo53eaeBb9FAL/4IprKGrWZRHiB/I/FHmQyUBgn/uh80=
  file: szofttech.pdf
  skip-cleanup: true
  overwrite: true
  on:
    repo: bme-notes/szofttech
